### ISSUE TITLE
How do you choose a feat at level 4 instead of an Ability Score? 

### ISSUE THREAD

**Issue by Somethingfrosty** [MalukuSeito/Character-Builder-5#4]
I says "choices for feats appear in the class tab", but there are no choices for feats.

**Comment by MalukuSeito** [comment]
Oh, the feats can be selected in the ability score tab, if the feats themselves need even more choices, those appear in the class tab.

**Comment by MalukuSeito** [comment]
![grafik](https://user-images.githubusercontent.com/17147116/38498890-3231bb96-3c06-11e8-9012-e18fa8954ceb.png)

**Comment by Somethingfrosty** [comment]
This is not an option for me. 
<img width="544" alt="nofeats" src="https://user-images.githubusercontent.com/12222678/38968403-1e9dea28-4340-11e8-949c-1ac11d475802.PNG">
I've tried extracting it from scratch, but that didn't help. Is this an issue with version I'm running? I'm on 1.0.0.0 because I can't find any newer executable and I can't get this project to build in Visual Studio.
I'm aware that only one feat would show up by default (the Grappler.xml) but I tried making additional ones and they don't work either. What's more is that the Character Builder Builder doesn't see it, or any other Feat in the root feat folder either. (It still sees the Feats/Boons and Feats/Metamagic feats)
![image](https://user-images.githubusercontent.com/12222678/38968617-199f0b78-4341-11e8-9677-8eb447bbbcac.png)

**Comment by MalukuSeito** [comment]
This is indeed quite odd, this might be due to an older version. I have added an automatic build for the latest version to GitHub, try downloading the latest release and check if the problem continues to exist
(Due to the nature of the auto build the files are somewhat hidden in their folders, you need to get the new Character Builder 5.exe and all dlls from the "Character Builder 5\bin\Release" folder and replace the ones in your version.

**Comment by MalukuSeito** [comment]
This is indeed quite odd, this might be due to an older version. I have added an automatic build for the latest version to GitHub, try downloading the latest release and check if the problem continues to exist
(Due to the nature of the auto build the files are somewhat hidden in their folders, you need to get the new Character Builder 5.exe and all dlls from the "Character Builder 5\bin\Release" folder and replace the ones in your version.
